### ISSUE TITLE
Is there a link to watch the talk?

### ISSUE THREAD

**Issue by vreality64** [aholachek/mobile-first-animation#2]
Thank you for sharing a good slide. After looking over it, I think it would be much better to watch it as video. Do you have a link to watch the talk? 😃

**Comment by szy0syz** [comment]
awsome code.
I am reading line by line.

**Comment by aholachek** [comment]
HI @vreality64, the [talk is on youtube](https://www.youtube.com/watch?v=JDDxR1a15Yo&feature=youtu.be&t=10664).

**Comment by aholachek** [comment]
I've added the link to the readme, thank you for pointing out that it was missing!
