### ISSUE TITLE
Janky Animations

### ISSUE THREAD

**Issue by amitnovick** [aholachek/mobile-first-animation#7]
Hi @aholachek,
Loved your talk! big fan of your work.

So I went and tried out the demos in this repo after struggling to improve performance of a "Card Swipe" interaction I've been developing recently for a mobile-first web app.

Unfortunately I couldn't get good performance on these.

I'm starting to be skeptical about the ability to display smooth animations on non-high-end devices (which is the majority of phones out there).

I ran these on a Xiaomi Redmi 3 phone (released 2016, about $150 USD, quite popular in asia)

## Music Player demo

![music-player-screenshot](https://user-images.githubusercontent.com/43674238/68489733-541c4700-0250-11ea-9b16-26794346297c.png)

Chrome-loadable Profile: 
[mobile-music-player-dev.json.zip](https://github.com/aholachek/mobile-first-animation/files/3825302/mobile-music-player-dev.json.zip)

## Email List demo

![email-list-screenshot](https://user-images.githubusercontent.com/43674238/68489570-0bfd2480-0250-11ea-817d-c6e8e20b6dc7.png)

Chrome-loadable Profile: 
[email-list.json.zip](https://github.com/aholachek/mobile-first-animation/files/3825304/email-list.json.zip)

**Comment by aholachek** [comment]
Hi @amitnovick, the chrome [usb debugging documentation](https://developers.google.com/web/tools/chrome-devtools/remote-debugging#screencast) warns that 
> Screencasts negatively affect frame rates. Disable screencasting while measuring scrolls or animations to get a more accurate picture of your page's performance.

Can you try turning off screencasting and profiling again?

I achieved acceptable, mostly 60fps performance on my inexpensive Android test device with all of the examples, however, I could totally imagine that some lower-end phones aren't up to the challenge of animating even one or two transforms. If the majority of your users are on <$100/150 phones there's definitely a cost/benefit analysis to be made if it's worth adding them at all.

**Comment by amitnovick** [comment]
Thanks for pointing out that screencasting might hurt the performance, and it does seem to have had some impact.

Some ancedata, this time with a production build of the app:
- **Email List** swiping an item left and right: 20-40fps
- **Email List** just scrolling down and back up: mostly 50-60fps but often times drops down to 10-20fps.
- **Music Drawer** swipe open and close: mostly 50-60fps but often times drops down to 05-20fps
- **Music Drawer** dragging the drawer around: same as above

Unfortunately, even with screencasting disabled and with the production build, the performance is still far from 60fps. Your Nokia 6 seems to be doing better, probably due to the GPU being almost 2 years newer. Hopefully in a few years we'll see this trend continuing, with mobile devices having better and better processing power for these interactions to become comparable to what high-end devices feel like today.

**Comment by aholachek** [comment]
Agreed. I'm going to add a disclaimer to the readme that says something like 
> While adhering to animation best practices can ensure that animations perform acceptably on newer "average", sub-$200 devices, there are some devices (older or very inexpensive phones) which will have trouble achieving minimal performance for even simple animations. Make sure to test animations on the phones of your target audience before committing to add them.
