### ISSUE TITLE
Question: why is it better to modify transform directly from a ref?

### ISSUE THREAD

**Issue by aecorredor** [aholachek/mobile-first-animation#9]
In comparison to the normal way of just updating the react component either through the style prop or through CSS?

**Comment by aholachek** [comment]
Hi, would you mind posting a link to the line of code that prompted this question? It could have just been an oversight on my part.

**Comment by aecorredor** [comment]
@aholachek Hey! This is one example: https://github.com/aholachek/mobile-first-animation/blob/master/src/EmailList/index.js#L66
